In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/grocery_data_mostrecent.csv")

In [ ]:
data.head()

         Date    Item  Price  Quantity Mode of Payment
0  04-01-2022    eggs   2.19         1      Debit Card
1  07-01-2022    eggs   2.19         2            Cash
2  07-01-2022   bread   2.99         3            Cash
3  07-01-2022    rice   5.99         1            Cash
4  08-01-2022  yogurt   1.99         1            Cash

In [ ]:
unique_counts = data['Item'].nunique()
unique_counts

124

In [ ]:
data['Date'] = pd.to_datetime(data['Date'], format='%d-%m-%Y')

# Sort the DataFrame by 'Date'
data.sort_values(by='Date', inplace=True)

# Group by 'Item' and get the first purchase date for each item
first_purchase_dates = data.groupby('Item')['Date'].transform('first')

# Add columns for previous purchase date and days after previous purchase
data['previous_purchase_date'] = data.groupby('Item')['Date'].shift().fillna(first_purchase_dates)
data['days_after_previous_purchase'] = (data['Date'] - data['previous_purchase_date']).dt.days

data

,Date,Item,Price,Quantity,Mode of Payment,previous_purchase_date,days_after_previous_purchase
0,2022-01-04,eggs,2.19,1,Debit Card,2022-01-04,0
1,2022-01-07,eggs,2.19,2,Cash,2022-01-04,3
2,2022-01-07,bread,2.99,3,Cash,2022-01-07,0
3,2022-01-07,rice,5.99,1,Cash,2022-01-07,0
4,2022-01-08,yogurt,1.99,1,Cash,2022-01-08,0
...,...,...,...,...,...,...,...
6721,2024-04-13,honey,4.99,5,Debit Card,2024-03-31,13
6720,2024-04-13,zucchini,1.49,1,Debit Card,2024-03-30,14
6719,2024-04-13,steak sauce,4.99,5,Debit Card,2024-03-23,21
6722,2024-04-13,pancake mix,2.99,3,Debit Card,2024-04-02,11
6727,2024-04-13,barbecue sauce,3.49,3,Debit Card,2024-03-25,19

In [ ]:
!pip install surprise

Requirement already satisfied: surprise in /usr/local/lib/python3.10/dist-packages (0.1)
Requirement already satisfied: scikit-surprise in /usr/local/lib/python3.10/dist-packages (from surprise) (1.1.3)
Requirement already satisfied: joblib>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-surprise->surprise) (1.4.0)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from scikit-surprise->surprise) (1.25.2)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from scikit-surprise->surprise) (1.11.4)

In [ ]:
import pandas as pd
from datetime import datetime, timedelta


# Convert 'Date' column to datetime
data['Date'] = pd.to_datetime(data['Date'])

# Calculate average time difference between consecutive purchases for each item
data['time_diff'] = data.groupby('Item')['Date'].diff().dt.days

# Calculate average time difference
average_time_diff = data.groupby('Item')['time_diff'].mean().to_dict()

# Predict next purchase date for each item
next_purchase_dates = {}
for item, avg_diff in average_time_diff.items():
    last_purchase_date = data[data['Item'] == item]['Date'].max()
    if pd.notna(last_purchase_date):
        next_purchase_dates[item] = last_purchase_date + timedelta(days=avg_diff)
    else:
        # If there's no previous purchase date, predict next purchase date as today
        next_purchase_dates[item] = datetime.now()

# Recommend items to be purchased next within the year
recommendations = []
current_date = datetime.now()
for item, next_purchase_date in next_purchase_dates.items():
    if next_purchase_date.year == current_date.year:
        recommendations.append((item, next_purchase_date))

# Sort recommendations by next purchase date
recommendations.sort(key=lambda x: x[1])

# Print recommendations
print("Items to be purchased next within the year:")
for i, (item, next_purchase_date) in enumerate(recommendations, 1):
    print(f"{i}. Item: {item}, Next Purchase Date: {next_purchase_date.strftime('%Y-%m-%d')}")

Items to be purchased next within the year:
1. Item: spaghetti sauce, Next Purchase Date: 2024-04-10
2. Item: tomatoes, Next Purchase Date: 2024-04-11
3. Item: garlic powder, Next Purchase Date: 2024-04-11
4. Item: lettuce, Next Purchase Date: 2024-04-12
5. Item: canned beans, Next Purchase Date: 2024-04-12
6. Item: frozen pies, Next Purchase Date: 2024-04-12
7. Item: bread, Next Purchase Date: 2024-04-13
8. Item: tea, Next Purchase Date: 2024-04-14
9. Item: frozen crepes, Next Purchase Date: 2024-04-14
10. Item: cake, Next Purchase Date: 2024-04-14
11. Item: rice, Next Purchase Date: 2024-04-14
12. Item: pasta, Next Purchase Date: 2024-04-15
13. Item: popcorn, Next Purchase Date: 2024-04-15
14. Item: maple syrup, Next Purchase Date: 2024-04-15
15. Item: milk, Next Purchase Date: 2024-04-16
16. Item: yogurt, Next Purchase Date: 2024-04-16
17. Item: jelly, Next Purchase Date: 2024-04-16
18. Item: soup, Next Purchase Date: 2024-04-16
19. Item: coffee, Next Purchase Date: 2024-04-16
20. Item: eggs, Next Purchase Date: 2024-04-16
21. Item: shrimp, Next Purchase Date: 2024-04-17
22. Item: onions, Next Purchase Date: 2024-04-17
23. Item: celery, Next Purchase Date: 2024-04-17
24. Item: carrots, Next Purchase Date: 2024-04-17
25. Item: dried fruits, Next Purchase Date: 2024-04-17
26. Item: frozen chicken nuggets, Next Purchase Date: 2024-04-17
27. Item: apples, Next Purchase Date: 2024-04-17
28. Item: vegetables, Next Purchase Date: 2024-04-18
29. Item: popcorn kernels, Next Purchase Date: 2024-04-18
30. Item: cookies, Next Purchase Date: 2024-04-18
31. Item: fruits, Next Purchase Date: 2024-04-18
32. Item: frozen breaded shrimp, Next Purchase Date: 2024-04-18
33. Item: pretzels, Next Purchase Date: 2024-04-18
34. Item: tuna, Next Purchase Date: 2024-04-19
35. Item: ice pops, Next Purchase Date: 2024-04-19
36. Item: bacon, Next Purchase Date: 2024-04-19
37. Item: paprika, Next Purchase Date: 2024-04-19
38. Item: frozen fruit bars, Next Purchase Date: 2024-04-19
39. Item: cooking spray, Next Purchase Date: 2024-04-19
40. Item: sauerkraut, Next Purchase Date: 2024-04-20
41. Item: frozen vegetables, Next Purchase Date: 2024-04-20
42. Item: beef, Next Purchase Date: 2024-04-20
43. Item: vinegar, Next Purchase Date: 2024-04-20
44. Item: crackers, Next Purchase Date: 2024-04-20
45. Item: guacamole, Next Purchase Date: 2024-04-20
46. Item: tortilla chips, Next Purchase Date: 2024-04-20
47. Item: water, Next Purchase Date: 2024-04-20
48. Item: mushrooms, Next Purchase Date: 2024-04-20
49. Item: sausages, Next Purchase Date: 2024-04-20
50. Item: bananas, Next Purchase Date: 2024-04-20
51. Item: instant noodles, Next Purchase Date: 2024-04-21
52. Item: crab, Next Purchase Date: 2024-04-21
53. Item: tortillas, Next Purchase Date: 2024-04-21
54. Item: ham, Next Purchase Date: 2024-04-21
55. Item: bread rolls, Next Purchase Date: 2024-04-21
56. Item: frozen breaded appetizers, Next Purchase Date: 2024-04-21
57. Item: avocado, Next Purchase Date: 2024-04-21
58. Item: potatoes, Next Purchase Date: 2024-04-21
59. Item: teriyaki sauce, Next Purchase Date: 2024-04-22
60. Item: lobster, Next Purchase Date: 2024-04-22
61. Item: frozen breakfast items, Next Purchase Date: 2024-04-22
62. Item: cinnamon, Next Purchase Date: 2024-04-22
63. Item: onion powder, Next Purchase Date: 2024-04-22
64. Item: frozen fries, Next Purchase Date: 2024-04-23
65. Item: olive oil, Next Purchase Date: 2024-04-23
66. Item: chips, Next Purchase Date: 2024-04-23
67. Item: mustard, Next Purchase Date: 2024-04-23
68. Item: cheese, Next Purchase Date: 2024-04-23
69. Item: salsa, Next Purchase Date: 2024-04-23
70. Item: ice cream, Next Purchase Date: 2024-04-23
71. Item: almond extract, Next Purchase Date: 2024-04-23
72. Item: taco seasoning, Next Purchase Date: 2024-04-24
73. Item: salad dressing, Next Purchase Date: 2024-04-24
74. Item: chicken, Next Purchase Date: 2024-04-24
75. Item: frozen meals, Next Purchase Date: 2024-04-24
76. Item: fish, Next Purchase Date: 2024-04-24
77. Item: orange juice, Next Purchase Date: 2024-04-24
78. Item: frozen breaded vegetables, Next Purchase Date: 2024-04-24
79. Item: pickles, Next Purchase Date: 2024-04-24
80. Item: soda, Next Purchase Date: 2024-04-24
81. Item: mayonnaise, Next Purchase Date: 2024-04-24
82. Item: frozen entrees, Next Purchase Date: 2024-04-25
83. Item: capers, Next Purchase Date: 2024-04-25
84. Item: zucchini, Next Purchase Date: 2024-04-25
85. Item: frozen pot pies, Next Purchase Date: 2024-04-25
86. Item: muffins, Next Purchase Date: 2024-04-25
87. Item: salmon, Next Purchase Date: 2024-04-25
88. Item: waffle mix, Next Purchase Date: 2024-04-25
89. Item: ketchup, Next Purchase Date: 2024-04-25
90. Item: frozen burritos, Next Purchase Date: 2024-04-25
91. Item: granola bars, Next Purchase Date: 2024-04-25
92. Item: frozen pizza, Next Purchase Date: 2024-04-26
93. Item: pancake mix, Next Purchase Date: 2024-04-26
94. Item: frozen waffles, Next Purchase Date: 2024-04-26
95. Item: barbecue sauce, Next Purchase Date: 2024-04-26
96. Item: honey, Next Purchase Date: 2024-04-26
97. Item: bell peppers, Next Purchase Date: 2024-04-26
98. Item: frozen dinners, Next Purchase Date: 2024-04-26
99. Item: curry powder, Next Purchase Date: 2024-04-27
100. Item: chili powder, Next Purchase Date: 2024-04-28
101. Item: frozen breaded jalapeno poppers, Next Purchase Date: 2024-04-28
102. Item: vanilla extract, Next Purchase Date: 2024-04-28
103. Item: dried herbs, Next Purchase Date: 2024-04-28
104. Item: cumin, Next Purchase Date: 2024-04-29
105. Item: nutmeg, Next Purchase Date: 2024-04-29
106. Item: bouillon cubes, Next Purchase Date: 2024-05-01
107. Item: olives, Next Purchase Date: 2024-05-02
108. Item: dried nuts, Next Purchase Date: 2024-05-02
109. Item: frozen breaded chicken, Next Purchase Date: 2024-05-03
110. Item: frozen fruits, Next Purchase Date: 2024-05-04
111. Item: frozen pancakes, Next Purchase Date: 2024-05-04
112. Item: instant rice, Next Purchase Date: 2024-05-05
113. Item: frozen breaded fish, Next Purchase Date: 2024-05-07
114. Item: pickle relish, Next Purchase Date: 2024-05-07
115. Item: frozen breaded mozzarella sticks, Next Purchase Date: 2024-05-08
116. Item: frozen breaded meatballs, Next Purchase Date: 2024-05-08
117. Item: frozen desserts, Next Purchase Date: 2024-05-08
118. Item: hot sauce, Next Purchase Date: 2024-05-08
119. Item: dried spices, Next Purchase Date: 2024-05-09
120. Item: soy sauce, Next Purchase Date: 2024-05-09
121. Item: frozen appetizers, Next Purchase Date: 2024-05-09
122. Item: steak sauce, Next Purchase Date: 2024-05-09
123. Item: peanut butter, Next Purchase Date: 2024-05-10
124. Item: frozen breakfast sandwiches, Next Purchase Date: 2024-05-10

In [ ]:
import pandas as pd
from datetime import datetime, timedelta

# Convert 'Date' column to datetime
data['Date'] = pd.to_datetime(data['Date'])

# Calculate average time difference between consecutive purchases for each item
data['time_diff'] = data.groupby('Item')['Date'].diff().dt.days

# Calculate average time difference
average_time_diff = data.groupby('Item')['time_diff'].mean().to_dict()

# Predict next purchase date for each item
next_purchase_dates = {}
for item, avg_diff in average_time_diff.items():
    last_purchase_date = data[data['Item'] == item]['Date'].max()
    if pd.notna(last_purchase_date):
        next_purchase_dates[item] = last_purchase_date + timedelta(days=avg_diff)
    else:
        # If there's no previous purchase date, predict next purchase date as today
        next_purchase_dates[item] = datetime.now()

# Recommend items to be purchased next within the year
recommendations = []
current_date = datetime.now()
for item, next_purchase_date in next_purchase_dates.items():
    if next_purchase_date.year == current_date.year:
        recommendations.append((item, next_purchase_date))

# Sort recommendations by next purchase date
recommendations.sort(key=lambda x: x[1])

# Print recommendations
print("Items to be purchased next within the year:")
for i, (item, next_purchase_date) in enumerate(recommendations, 1):
    print(f"{i}. Item: {item}, Next Purchase Date: {next_purchase_date.strftime('%Y-%m-%d')}")

# Create a DataFrame from recommendations
df_recommendations = pd.DataFrame(recommendations, columns=['Item', 'Next Purchase Date'])

Items to be purchased next within the year:
1. Item: spaghetti sauce, Next Purchase Date: 2024-04-10
2. Item: tomatoes, Next Purchase Date: 2024-04-11
3. Item: garlic powder, Next Purchase Date: 2024-04-11
4. Item: lettuce, Next Purchase Date: 2024-04-12
5. Item: canned beans, Next Purchase Date: 2024-04-12
6. Item: frozen pies, Next Purchase Date: 2024-04-12
7. Item: bread, Next Purchase Date: 2024-04-13
8. Item: tea, Next Purchase Date: 2024-04-14
9. Item: frozen crepes, Next Purchase Date: 2024-04-14
10. Item: cake, Next Purchase Date: 2024-04-14
11. Item: rice, Next Purchase Date: 2024-04-14
12. Item: pasta, Next Purchase Date: 2024-04-15
13. Item: popcorn, Next Purchase Date: 2024-04-15
14. Item: maple syrup, Next Purchase Date: 2024-04-15
15. Item: milk, Next Purchase Date: 2024-04-16
16. Item: yogurt, Next Purchase Date: 2024-04-16
17. Item: jelly, Next Purchase Date: 2024-04-16
18. Item: soup, Next Purchase Date: 2024-04-16
19. Item: coffee, Next Purchase Date: 2024-04-16
20. Item: eggs, Next Purchase Date: 2024-04-16
21. Item: shrimp, Next Purchase Date: 2024-04-17
22. Item: onions, Next Purchase Date: 2024-04-17
23. Item: celery, Next Purchase Date: 2024-04-17
24. Item: carrots, Next Purchase Date: 2024-04-17
25. Item: dried fruits, Next Purchase Date: 2024-04-17
26. Item: frozen chicken nuggets, Next Purchase Date: 2024-04-17
27. Item: apples, Next Purchase Date: 2024-04-17
28. Item: vegetables, Next Purchase Date: 2024-04-18
29. Item: popcorn kernels, Next Purchase Date: 2024-04-18
30. Item: cookies, Next Purchase Date: 2024-04-18
31. Item: fruits, Next Purchase Date: 2024-04-18
32. Item: frozen breaded shrimp, Next Purchase Date: 2024-04-18
33. Item: pretzels, Next Purchase Date: 2024-04-18
34. Item: tuna, Next Purchase Date: 2024-04-19
35. Item: ice pops, Next Purchase Date: 2024-04-19
36. Item: bacon, Next Purchase Date: 2024-04-19
37. Item: paprika, Next Purchase Date: 2024-04-19
38. Item: frozen fruit bars, Next Purchase Date: 2024-04-19
39. Item: cooking spray, Next Purchase Date: 2024-04-19
40. Item: sauerkraut, Next Purchase Date: 2024-04-20
41. Item: frozen vegetables, Next Purchase Date: 2024-04-20
42. Item: beef, Next Purchase Date: 2024-04-20
43. Item: vinegar, Next Purchase Date: 2024-04-20
44. Item: crackers, Next Purchase Date: 2024-04-20
45. Item: guacamole, Next Purchase Date: 2024-04-20
46. Item: tortilla chips, Next Purchase Date: 2024-04-20
47. Item: water, Next Purchase Date: 2024-04-20
48. Item: mushrooms, Next Purchase Date: 2024-04-20
49. Item: sausages, Next Purchase Date: 2024-04-20
50. Item: bananas, Next Purchase Date: 2024-04-20
51. Item: instant noodles, Next Purchase Date: 2024-04-21
52. Item: crab, Next Purchase Date: 2024-04-21
53. Item: tortillas, Next Purchase Date: 2024-04-21
54. Item: ham, Next Purchase Date: 2024-04-21
55. Item: bread rolls, Next Purchase Date: 2024-04-21
56. Item: frozen breaded appetizers, Next Purchase Date: 2024-04-21
57. Item: avocado, Next Purchase Date: 2024-04-21
58. Item: potatoes, Next Purchase Date: 2024-04-21
59. Item: teriyaki sauce, Next Purchase Date: 2024-04-22
60. Item: lobster, Next Purchase Date: 2024-04-22
61. Item: frozen breakfast items, Next Purchase Date: 2024-04-22
62. Item: cinnamon, Next Purchase Date: 2024-04-22
63. Item: onion powder, Next Purchase Date: 2024-04-22
64. Item: frozen fries, Next Purchase Date: 2024-04-23
65. Item: olive oil, Next Purchase Date: 2024-04-23
66. Item: chips, Next Purchase Date: 2024-04-23
67. Item: mustard, Next Purchase Date: 2024-04-23
68. Item: cheese, Next Purchase Date: 2024-04-23
69. Item: salsa, Next Purchase Date: 2024-04-23
70. Item: ice cream, Next Purchase Date: 2024-04-23
71. Item: almond extract, Next Purchase Date: 2024-04-23
72. Item: taco seasoning, Next Purchase Date: 2024-04-24
73. Item: salad dressing, Next Purchase Date: 2024-04-24
74. Item: chicken, Next Purchase Date: 2024-04-24
75. Item: frozen meals, Next Purchase Date: 2024-04-24
76. Item: fish, Next Purchase Date: 2024-04-24
77. Item: orange juice, Next Purchase Date: 2024-04-24
78. Item: frozen breaded vegetables, Next Purchase Date: 2024-04-24
79. Item: pickles, Next Purchase Date: 2024-04-24
80. Item: soda, Next Purchase Date: 2024-04-24
81. Item: mayonnaise, Next Purchase Date: 2024-04-24
82. Item: frozen entrees, Next Purchase Date: 2024-04-25
83. Item: capers, Next Purchase Date: 2024-04-25
84. Item: zucchini, Next Purchase Date: 2024-04-25
85. Item: frozen pot pies, Next Purchase Date: 2024-04-25
86. Item: muffins, Next Purchase Date: 2024-04-25
87. Item: salmon, Next Purchase Date: 2024-04-25
88. Item: waffle mix, Next Purchase Date: 2024-04-25
89. Item: ketchup, Next Purchase Date: 2024-04-25
90. Item: frozen burritos, Next Purchase Date: 2024-04-25
91. Item: granola bars, Next Purchase Date: 2024-04-25
92. Item: frozen pizza, Next Purchase Date: 2024-04-26
93. Item: pancake mix, Next Purchase Date: 2024-04-26
94. Item: frozen waffles, Next Purchase Date: 2024-04-26
95. Item: barbecue sauce, Next Purchase Date: 2024-04-26
96. Item: honey, Next Purchase Date: 2024-04-26
97. Item: bell peppers, Next Purchase Date: 2024-04-26
98. Item: frozen dinners, Next Purchase Date: 2024-04-26
99. Item: curry powder, Next Purchase Date: 2024-04-27
100. Item: chili powder, Next Purchase Date: 2024-04-28
101. Item: frozen breaded jalapeno poppers, Next Purchase Date: 2024-04-28
102. Item: vanilla extract, Next Purchase Date: 2024-04-28
103. Item: dried herbs, Next Purchase Date: 2024-04-28
104. Item: cumin, Next Purchase Date: 2024-04-29
105. Item: nutmeg, Next Purchase Date: 2024-04-29
106. Item: bouillon cubes, Next Purchase Date: 2024-05-01
107. Item: olives, Next Purchase Date: 2024-05-02
108. Item: dried nuts, Next Purchase Date: 2024-05-02
109. Item: frozen breaded chicken, Next Purchase Date: 2024-05-03
110. Item: frozen fruits, Next Purchase Date: 2024-05-04
111. Item: frozen pancakes, Next Purchase Date: 2024-05-04
112. Item: instant rice, Next Purchase Date: 2024-05-05
113. Item: frozen breaded fish, Next Purchase Date: 2024-05-07
114. Item: pickle relish, Next Purchase Date: 2024-05-07
115. Item: frozen breaded mozzarella sticks, Next Purchase Date: 2024-05-08
116. Item: frozen breaded meatballs, Next Purchase Date: 2024-05-08
117. Item: frozen desserts, Next Purchase Date: 2024-05-08
118. Item: hot sauce, Next Purchase Date: 2024-05-08
119. Item: dried spices, Next Purchase Date: 2024-05-09
120. Item: soy sauce, Next Purchase Date: 2024-05-09
121. Item: frozen appetizers, Next Purchase Date: 2024-05-09
122. Item: steak sauce, Next Purchase Date: 2024-05-09
123. Item: peanut butter, Next Purchase Date: 2024-05-10
124. Item: frozen breakfast sandwiches, Next Purchase Date: 2024-05-10

In [ ]:
df_recommendations['Next Purchase Date'] = pd.to_datetime(df_recommendations['Next Purchase Date']).dt.date

In [ ]:
df_recommendations

                            Item Next Purchase Date
0                spaghetti sauce         2024-04-10
1                       tomatoes         2024-04-11
2                  garlic powder         2024-04-11
3                        lettuce         2024-04-12
4                   canned beans         2024-04-12
..                           ...                ...
119                    soy sauce         2024-05-09
120            frozen appetizers         2024-05-09
121                  steak sauce         2024-05-09
122                peanut butter         2024-05-10
123  frozen breakfast sandwiches         2024-05-10

[124 rows x 2 columns]

In [ ]:
df_recommendations.to_csv('recommendations.csv', index=False)

In [ ]:
import pandas as pd
from datetime import datetime, timedelta

# Convert 'Date' column to datetime
data['Date'] = pd.to_datetime(data['Date'])

# Calculate average time difference between consecutive purchases for each item
data['time_diff'] = data.groupby('Item')['Date'].diff().dt.days

# Calculate average time difference
average_time_diff = data.groupby('Item')['time_diff'].mean().to_dict()

# Calculate average quantity purchased for each item and round to nearest integer
average_quantity = data.groupby('Item')['Quantity'].mean().round().astype(int).to_dict()

# Predict next purchase date and quantity for each item
next_purchase_info = {}
for item, avg_diff in average_time_diff.items():
    last_purchase_date = data[data['Item'] == item]['Date'].max()
    if pd.notna(last_purchase_date):
        next_purchase_date = last_purchase_date + timedelta(days=avg_diff)
    else:
        # If there's no previous purchase date, predict next purchase date as today
        next_purchase_date = datetime.now()

    # Predict quantity
    predicted_quantity = average_quantity.get(item, 0)  # Default to 0 if no previous data is available

    next_purchase_info[item] = {'Next Purchase Date': next_purchase_date, 'Predicted Quantity': predicted_quantity}

# Recommend items to be purchased next within the year
recommendations = []
current_date = datetime.now()
for item, info in next_purchase_info.items():
    next_purchase_date = info['Next Purchase Date']
    if next_purchase_date.year == current_date.year:
        recommendations.append((item, next_purchase_date, info['Predicted Quantity']))

# Sort recommendations by next purchase date
recommendations.sort(key=lambda x: x[1])

# Print recommendations
print("Items to be purchased next within the year:")
for i, (item, next_purchase_date, predicted_quantity) in enumerate(recommendations, 1):
    print(f"{i}. Item: {item}, Next Purchase Date: {next_purchase_date.strftime('%Y-%m-%d')}, Predicted Quantity: {predicted_quantity}")

# Create a DataFrame from recommendations
df_recommendations = pd.DataFrame(recommendations, columns=['Item', 'Next Purchase Date', 'Predicted Quantity'])

Items to be purchased next within the year:
1. Item: spaghetti sauce, Next Purchase Date: 2024-04-10, Predicted Quantity: 3
2. Item: tomatoes, Next Purchase Date: 2024-04-11, Predicted Quantity: 3
3. Item: garlic powder, Next Purchase Date: 2024-04-11, Predicted Quantity: 3
4. Item: lettuce, Next Purchase Date: 2024-04-12, Predicted Quantity: 3
5. Item: canned beans, Next Purchase Date: 2024-04-12, Predicted Quantity: 3
6. Item: frozen pies, Next Purchase Date: 2024-04-12, Predicted Quantity: 3
7. Item: bread, Next Purchase Date: 2024-04-13, Predicted Quantity: 3
8. Item: tea, Next Purchase Date: 2024-04-14, Predicted Quantity: 3
9. Item: frozen crepes, Next Purchase Date: 2024-04-14, Predicted Quantity: 3
10. Item: cake, Next Purchase Date: 2024-04-14, Predicted Quantity: 3
11. Item: rice, Next Purchase Date: 2024-04-14, Predicted Quantity: 3
12. Item: pasta, Next Purchase Date: 2024-04-15, Predicted Quantity: 3
13. Item: popcorn, Next Purchase Date: 2024-04-15, Predicted Quantity: 3
14. Item: maple syrup, Next Purchase Date: 2024-04-15, Predicted Quantity: 3
15. Item: milk, Next Purchase Date: 2024-04-16, Predicted Quantity: 3
16. Item: yogurt, Next Purchase Date: 2024-04-16, Predicted Quantity: 3
17. Item: jelly, Next Purchase Date: 2024-04-16, Predicted Quantity: 3
18. Item: soup, Next Purchase Date: 2024-04-16, Predicted Quantity: 3
19. Item: coffee, Next Purchase Date: 2024-04-16, Predicted Quantity: 3
20. Item: eggs, Next Purchase Date: 2024-04-16, Predicted Quantity: 3
21. Item: shrimp, Next Purchase Date: 2024-04-17, Predicted Quantity: 3
22. Item: onions, Next Purchase Date: 2024-04-17, Predicted Quantity: 3
23. Item: celery, Next Purchase Date: 2024-04-17, Predicted Quantity: 3
24. Item: carrots, Next Purchase Date: 2024-04-17, Predicted Quantity: 3
25. Item: dried fruits, Next Purchase Date: 2024-04-17, Predicted Quantity: 3
26. Item: frozen chicken nuggets, Next Purchase Date: 2024-04-17, Predicted Quantity: 3
27. Item: apples, Next Purchase Date: 2024-04-17, Predicted Quantity: 3
28. Item: vegetables, Next Purchase Date: 2024-04-18, Predicted Quantity: 3
29. Item: popcorn kernels, Next Purchase Date: 2024-04-18, Predicted Quantity: 3
30. Item: cookies, Next Purchase Date: 2024-04-18, Predicted Quantity: 3
31. Item: fruits, Next Purchase Date: 2024-04-18, Predicted Quantity: 3
32. Item: frozen breaded shrimp, Next Purchase Date: 2024-04-18, Predicted Quantity: 3
33. Item: pretzels, Next Purchase Date: 2024-04-18, Predicted Quantity: 3
34. Item: tuna, Next Purchase Date: 2024-04-19, Predicted Quantity: 3
35. Item: ice pops, Next Purchase Date: 2024-04-19, Predicted Quantity: 3
36. Item: bacon, Next Purchase Date: 2024-04-19, Predicted Quantity: 3
37. Item: paprika, Next Purchase Date: 2024-04-19, Predicted Quantity: 3
38. Item: frozen fruit bars, Next Purchase Date: 2024-04-19, Predicted Quantity: 3
39. Item: cooking spray, Next Purchase Date: 2024-04-19, Predicted Quantity: 3
40. Item: sauerkraut, Next Purchase Date: 2024-04-20, Predicted Quantity: 3
41. Item: frozen vegetables, Next Purchase Date: 2024-04-20, Predicted Quantity: 3
42. Item: beef, Next Purchase Date: 2024-04-20, Predicted Quantity: 3
43. Item: vinegar, Next Purchase Date: 2024-04-20, Predicted Quantity: 3
44. Item: crackers, Next Purchase Date: 2024-04-20, Predicted Quantity: 3
45. Item: guacamole, Next Purchase Date: 2024-04-20, Predicted Quantity: 3
46. Item: tortilla chips, Next Purchase Date: 2024-04-20, Predicted Quantity: 3
47. Item: water, Next Purchase Date: 2024-04-20, Predicted Quantity: 3
48. Item: mushrooms, Next Purchase Date: 2024-04-20, Predicted Quantity: 3
49. Item: sausages, Next Purchase Date: 2024-04-20, Predicted Quantity: 3
50. Item: bananas, Next Purchase Date: 2024-04-20, Predicted Quantity: 3
51. Item: instant noodles, Next Purchase Date: 2024-04-21, Predicted Quantity: 2
52. Item: crab, Next Purchase Date: 2024-04-21, Predicted Quantity: 3
53. Item: tortillas, Next Purchase Date: 2024-04-21, Predicted Quantity: 3
54. Item: ham, Next Purchase Date: 2024-04-21, Predicted Quantity: 3
55. Item: bread rolls, Next Purchase Date: 2024-04-21, Predicted Quantity: 3
56. Item: frozen breaded appetizers, Next Purchase Date: 2024-04-21, Predicted Quantity: 3
57. Item: avocado, Next Purchase Date: 2024-04-21, Predicted Quantity: 3
58. Item: potatoes, Next Purchase Date: 2024-04-21, Predicted Quantity: 3
59. Item: teriyaki sauce, Next Purchase Date: 2024-04-22, Predicted Quantity: 3
60. Item: lobster, Next Purchase Date: 2024-04-22, Predicted Quantity: 3
61. Item: frozen breakfast items, Next Purchase Date: 2024-04-22, Predicted Quantity: 3
62. Item: cinnamon, Next Purchase Date: 2024-04-22, Predicted Quantity: 3
63. Item: onion powder, Next Purchase Date: 2024-04-22, Predicted Quantity: 3
64. Item: frozen fries, Next Purchase Date: 2024-04-23, Predicted Quantity: 2
65. Item: olive oil, Next Purchase Date: 2024-04-23, Predicted Quantity: 3
66. Item: chips, Next Purchase Date: 2024-04-23, Predicted Quantity: 3
67. Item: mustard, Next Purchase Date: 2024-04-23, Predicted Quantity: 3
68. Item: cheese, Next Purchase Date: 2024-04-23, Predicted Quantity: 3
69. Item: salsa, Next Purchase Date: 2024-04-23, Predicted Quantity: 3
70. Item: ice cream, Next Purchase Date: 2024-04-23, Predicted Quantity: 3
71. Item: almond extract, Next Purchase Date: 2024-04-23, Predicted Quantity: 3
72. Item: taco seasoning, Next Purchase Date: 2024-04-24, Predicted Quantity: 3
73. Item: salad dressing, Next Purchase Date: 2024-04-24, Predicted Quantity: 3
74. Item: chicken, Next Purchase Date: 2024-04-24, Predicted Quantity: 3
75. Item: frozen meals, Next Purchase Date: 2024-04-24, Predicted Quantity: 3
76. Item: fish, Next Purchase Date: 2024-04-24, Predicted Quantity: 3
77. Item: orange juice, Next Purchase Date: 2024-04-24, Predicted Quantity: 3
78. Item: frozen breaded vegetables, Next Purchase Date: 2024-04-24, Predicted Quantity: 3
79. Item: pickles, Next Purchase Date: 2024-04-24, Predicted Quantity: 3
80. Item: soda, Next Purchase Date: 2024-04-24, Predicted Quantity: 3
81. Item: mayonnaise, Next Purchase Date: 2024-04-24, Predicted Quantity: 3
82. Item: frozen entrees, Next Purchase Date: 2024-04-25, Predicted Quantity: 3
83. Item: capers, Next Purchase Date: 2024-04-25, Predicted Quantity: 3
84. Item: zucchini, Next Purchase Date: 2024-04-25, Predicted Quantity: 3
85. Item: frozen pot pies, Next Purchase Date: 2024-04-25, Predicted Quantity: 3
86. Item: muffins, Next Purchase Date: 2024-04-25, Predicted Quantity: 3
87. Item: salmon, Next Purchase Date: 2024-04-25, Predicted Quantity: 3
88. Item: waffle mix, Next Purchase Date: 2024-04-25, Predicted Quantity: 3
89. Item: ketchup, Next Purchase Date: 2024-04-25, Predicted Quantity: 3
90. Item: frozen burritos, Next Purchase Date: 2024-04-25, Predicted Quantity: 3
91. Item: granola bars, Next Purchase Date: 2024-04-25, Predicted Quantity: 3
92. Item: frozen pizza, Next Purchase Date: 2024-04-26, Predicted Quantity: 3
93. Item: pancake mix, Next Purchase Date: 2024-04-26, Predicted Quantity: 3
94. Item: frozen waffles, Next Purchase Date: 2024-04-26, Predicted Quantity: 3
95. Item: barbecue sauce, Next Purchase Date: 2024-04-26, Predicted Quantity: 3
96. Item: honey, Next Purchase Date: 2024-04-26, Predicted Quantity: 3
97. Item: bell peppers, Next Purchase Date: 2024-04-26, Predicted Quantity: 3
98. Item: frozen dinners, Next Purchase Date: 2024-04-26, Predicted Quantity: 3
99. Item: curry powder, Next Purchase Date: 2024-04-27, Predicted Quantity: 3
100. Item: chili powder, Next Purchase Date: 2024-04-28, Predicted Quantity: 3
101. Item: frozen breaded jalapeno poppers, Next Purchase Date: 2024-04-28, Predicted Quantity: 3
102. Item: vanilla extract, Next Purchase Date: 2024-04-28, Predicted Quantity: 3
103. Item: dried herbs, Next Purchase Date: 2024-04-28, Predicted Quantity: 3
104. Item: cumin, Next Purchase Date: 2024-04-29, Predicted Quantity: 3
105. Item: nutmeg, Next Purchase Date: 2024-04-29, Predicted Quantity: 3
106. Item: bouillon cubes, Next Purchase Date: 2024-05-01, Predicted Quantity: 3
107. Item: olives, Next Purchase Date: 2024-05-02, Predicted Quantity: 3
108. Item: dried nuts, Next Purchase Date: 2024-05-02, Predicted Quantity: 3
109. Item: frozen breaded chicken, Next Purchase Date: 2024-05-03, Predicted Quantity: 3
110. Item: frozen fruits, Next Purchase Date: 2024-05-04, Predicted Quantity: 3
111. Item: frozen pancakes, Next Purchase Date: 2024-05-04, Predicted Quantity: 3
112. Item: instant rice, Next Purchase Date: 2024-05-05, Predicted Quantity: 3
113. Item: frozen breaded fish, Next Purchase Date: 2024-05-07, Predicted Quantity: 3
114. Item: pickle relish, Next Purchase Date: 2024-05-07, Predicted Quantity: 3
115. Item: frozen breaded mozzarella sticks, Next Purchase Date: 2024-05-08, Predicted Quantity: 3
116. Item: frozen breaded meatballs, Next Purchase Date: 2024-05-08, Predicted Quantity: 3
117. Item: frozen desserts, Next Purchase Date: 2024-05-08, Predicted Quantity: 3
118. Item: hot sauce, Next Purchase Date: 2024-05-08, Predicted Quantity: 3
119. Item: dried spices, Next Purchase Date: 2024-05-09, Predicted Quantity: 3
120. Item: soy sauce, Next Purchase Date: 2024-05-09, Predicted Quantity: 3
121. Item: frozen appetizers, Next Purchase Date: 2024-05-09, Predicted Quantity: 3
122. Item: steak sauce, Next Purchase Date: 2024-05-09, Predicted Quantity: 3
123. Item: peanut butter, Next Purchase Date: 2024-05-10, Predicted Quantity: 3
124. Item: frozen breakfast sandwiches, Next Purchase Date: 2024-05-10, Predicted Quantity: 3